# Generated by Django 4.2.2 on 2023-06-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='sin nombrar', max_length=300, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='sin descripción', max_length=300, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('fecha_de_registro', models.DateField(default='sin fecha', max_length=300, verbose_name='Fecha de registro')),
                ('estatus', models.CharField(default='sin estatus', max_length=300, verbose_name='Estatus')),
            ],
        ),
    ]
